
spring:
  profiles:
    active: activemq-dev
camel:
  springboot:
    shutdown-timeout: 2

---

spring:
  profiles: mock

startRoute: direct:input
fromRoute: file:data/input?delete=true&readLock=none
toRoute: mock:output

message: MOCK Environnement

---

spring:
  profiles: activemq-dev
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5431/player1
#    username: player2
#    password: player2


startRoute: timer:hello?period=10s
fromRouteFile: file:data/input?delete=true&readLock=none
#fromRoute: activemq:inputItemQueue
toRoute: file:data/output

fromRouteActivemq: activemq:inputItemQueue
toRouteActivemq: log:?level=INFO&showBody=true
toRouteActivemq1: log:?level=INFO&showBody=false

message: DEV Environnement


---

spring:
  profiles: dev
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5431/player1
#    username: player2
#    password: player2


startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/output

message: DEV Environnement



---

spring:
  profiles: stage
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5431/localDB
#    username: player2
#    password: player2

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/output

message: STAGE Environnement

---
spring:
  profiles: prod
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5431/localDB
#    username: player2
#    password: player2

startRoute: timer:hello?period=10s
fromRoute: file:data/input?delete=true&readLock=none
toRoute: file:data/output

message: PROD Environnement


